# -*- coding: utf-8 -*-
"""Getting Started with titanic

Automatically generated by Colaboratory.

Original file is located at
    https://colab.research.google.com/drive/1H2aeCWFFaPGjCh3aFFtrwqEHV6ETzKCN
"""

#importing required libraries
import numpy as np 
import pandas as pd

#Loading Dataset
from google.colab import files
uploaded = files.upload()

#Loading Dataset
train_data = pd.read_csv("train.csv")
train_data.head()

train_data.describe()

#uploading test.csv file
from google.colab import files
uploaded=files.upload()

#Loading data from test.csv
test_data = pd.read_csv("test.csv")
test_data.head()

#The below code calculates the percentage of female passengers (in train.csv) who survived.
women = train_data.loc[train_data.Sex == 'female']["Survived"]
rate_women = sum(women)/len(women)

print("% of women who survived:", rate_women)

#The below code calculates the percentage of male passengers (in train.csv) who survived.
men = train_data.loc[train_data.Sex == 'male']["Survived"]
rate_men = sum(men)/len(men)

print("% of men who survived:", rate_men)

#We'll build what's known as a random forest model
from sklearn.ensemble import RandomForestClassifier

y = train_data["Survived"]

features = ["Pclass", "Sex", "SibSp", "Parch"]
X = pd.get_dummies(train_data[features])
X_test = pd.get_dummies(test_data[features])

model = RandomForestClassifier(n_estimators=100, max_depth=5, random_state=1)
model.fit(X, y)
predictions = model.predict(X_test)

output = pd.DataFrame({'PassengerId': test_data.PassengerId, 'Survived': predictions})
output.to_csv('my_submission.csv', index=False)
print("Your submission was successfully saved!")